spring:
  application:
    name: demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.134:3306/activitydemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


  thymeleaf:
      cache: false # 开发时关闭缓存,不然没法看到实时页面
      mode: HTML # 用非严格的 HTML
      encoding: UTF-8
      servlet:
        content-type: text/html
#  activiti:
#    check-process-definitions: false

#  security:
#    user:
#      password: 1234
#      name: user
